---
- name: Установка nginx и php-fpm.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - nginx
    - php-fpm

- name: Проверка запуска nginx сервиса.
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Проверка запуска php-fpm сервиса.
  ansible.builtin.service:
    name: php8.1-fpm
    state: started
    enabled: true

- name: Создание DocumentRoot директории.
  ansible.builtin.file:
    path: "{{ nginx_document_root }}"
    state: directory
    mode: "755"
    owner: "{{ exec_user }}"

- name: Изменение default.conf по шаблону.
  ansible.builtin.template:
    src: localhost.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: preserve
  notify:
    - Reload Nginx

- name: Изменение nginx.conf по шаблону.
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: preserve
  notify:
    - Перезагрузка Nginx

- name: Копирование index.php файла.
  ansible.builtin.copy:
    src: index.php
    dest: "{{ nginx_document_root }}/index.php"
    mode: preserve
  notify:
    - Перезагрузка Nginx
