---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Install php-fpm
  ansible.builtin.apt:
    name: php-fpm
    state: present

- name: Ensure nginx service is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Ensure php-fpm service is running
  ansible.builtin.service:
    name: php8.1-fpm
    state: started
    enabled: true

- name: Create DocumentRoot directory
  ansible.builtin.file:
    path: "{{ nginx_document_root }}"
    state: directory
    mode: "755"
    owner: "{{ exec_user }}"

- name: Edit default.conf
  ansible.builtin.template:
    src: localhost.conf.j2
    dest: /etc/nginx/sites-available/default
    mode: preserve
  notify:
    - Reload Nginx

- name: Edit nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: preserve
  notify:
    - Reload Nginx

- name: Copy index.php file
  ansible.builtin.copy:
    src: index.php
    dest: "{{ nginx_document_root }}/index.php"
    mode: preserve
  notify:
    - Reload Nginx
