---
# tasks file for dnsmasq
- name: Install dnsmasq
  ansible.builtin.package:
    name: dnsmasq
    state: present

- name: Copy dnsmasq.conf file
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/
    mode: "660"
  notify:
    - Restart dnsmasq

- name: Ensure dnsmasq service is enabled and started
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: true
